### ISSUE TITLE
Reverting to normal behavior 3P h-scene

### ISSUE THREAD

**Issue by RichardB73** [Animal42069/AI_BetterPenetration#1]
Hi, I was playing around with your plugin and liked it a lot.
After a while I noticed when doing a 3P scene the penis goes back to normal size and does not even penetrate the girl riding it.
It now stays behind her and has no connection with the vagina at all.

Not sure if it is a known issue or just something happening on my side.
The other scenes i played so far looked fine and the length/girth/softness options seem to be working as intended.

**Comment by Animal42069** [comment]
What does 3p scene mean?  3 person?

**Comment by RichardB73** [comment]
yes 3 person scene 1 guy 2 girls

**Comment by Animal42069** [comment]
Ya I didn't write it with 3 person in mind, didn't know that was a
possibility in AI.  I'd have to figure a way to distinguish which woman is
the target.  It's probably trying to Target the wrong girl and that's why
it's bugging out

**Comment by RichardB73** [comment]
I only seen 1 3 person scene so far not sure if there are more either.
You have to make 1 girl follow you and then ask the 2nd girl if she wants a threesome to initiate it.
The target would be the one you invite to follow you, maybe you can do something with that.

**Comment by Animal42069** [comment]
Ah cool didn't know that, next time I have some free time I'll try out some
fixes

**Comment by Animal42069** [comment]
It's an easy fix, the first girl in the list is always the target.  Some of her variables we're getting overwritten by the 2nd.  I'll put out a fix in the next day or so

**Comment by RichardB73** [comment]
Sorry should have closed this already since you fixed it weeks ago, thanks for the fix.
